# hash-identificacao: f8b8729ea16441fe6c700c5cedf41aac601bb30c295f48b8fb407154ff6364e4

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=dadospessoais

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true
